rule_files:
  - 'alert.rules.yml'
  - 'services.rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: node-local
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: node-10.35
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.10.35:9100']

  - job_name: 'nginx-10.35'
    static_configs:
    - targets: ['192.168.10.35:9113']

  - job_name: 'blackbox-http_2xx-general'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_2xx-general] 
    static_configs:
      - targets:
        - https://lms.skillfactory.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

